name: 'Hello World'

description: 'Greet someone'

runs:
  using: "composite"
  steps:  
    - name: Adding myTask to build.gradle
      run: |
        printf "\n\ntasks.register('myTask') {\n\tprintln 'Hello from myTask!'\n}" >> build.gradle
      shell: bash
    - name: Execute myTask
      run: |
        chmod +x gradlew
        ./gradlew myTask
      shell: bash
