name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - name: Chmod
      run: chmod +x gradlew
      shell: bash
    - name: Execute myTask
      run: ./gradlew myTask
      shell: bash

    - name: Pushing a new file
      run: |
        echo "content" > new-file.txt
        git add new-file.txt
        git commit -m "Add a new file"
        git push
      shell: bash
