name: 'Test Github Action'

description: 'Test Github Action Description'

inputs:
  token:
    description: 'Github token'
    required: true

  targetClasses:
    description: 'Classes for the test generation'
    default: ""

  testsDirectory:
    description: 'Path to generated tests'
    default: .utbot/test

  pushTests:
    description: 'Push generated tests to the repository or not'
    default: true

runs:
  using: "composite"
  steps:  
    - run: chmod +x gradlew
      shell: bash

    - name: Run testGradleTask
      uses: gradle/gradle-build-action@v2
      with:
        arguments: testGradleTask -PtargetClasses=${{ inputs.targetClasses }} -PtestsDirectory=${{ inputs.testsDirectory }} -PpushTests=${{ inputs.pushTests }}

    - name: Configure git user
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
      shell: bash

    - name: Commit generated tests
      run: |
        if ${{ inputs.pushTests }}  # if the user allows push
        then
          git add ${{ inputs.testsDirectory }}
          if ! git diff --quiet HEAD ${{ inputs.testsDirectory }}  # if there are changes
          then
            git commit -m "[UTBot]: Add generated tests"
            git push ${{ github.ref }}
          fi
        fi
      shell: bash

    - name: Push changes
      if: ${{ inputs.pushTests == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.token }}
        branch: ${{ github.ref }}

    - name: Upload SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: .utbot/utbot.sarif
