name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - run: chmod +x gradlew
    - name: Execute myTask
      run: ./gradlew myTask
